current_env: dev

default: &default
  GRIDSIZE: 15
  COOKIE_SECURE: false
  OBSNUMBER: 15
  COINNUMBER: 5

dev:
  <<: *default
  DOMAIN: localhost
  PORT: 8080
  ENDPOINT: localhost:8080

prd:
  <<: *default
  DOMAIN: go-pickup.com
  ENDPOINT: go-pickup.com
  COOKIE_SECURE: true