current_env: dev

default: &default
  # server settings
  COOKIE_SECURE: false

  # game settings
  GRIDSIZE: 15
  OBSNUMBER: 15
  COINNUMBER: 10
  DIAMOND: 2
  RUNNING_GAME_JOIN_PROTECT: false

dev:
  <<: *default
  DOMAIN: localhost
  PORT: 8080
  ENDPOINT: localhost:8080

prd:
  <<: *default
  DOMAIN: go-pickup.com
  ENDPOINT: go-pickup.com
  COOKIE_SECURE: true